"""Simple inference stub used by the UI during development.

This file provides `run_pipeline(article_text)` which returns a dict with keys:
- question: str
- options: list[str] (length 4)
- correct_index: int (0-3)
- hints: list[str] (3 items)
- explanation: optional str

When model artifacts are present under `models/` this can be extended to call real models.
"""
from pathlib import Path
import random
import json
import joblib


def _simple_candidates(article: str):
    words = [w for w in article.split() if len(w) > 3]
    random.shuffle(words)
    # create 3 short distractors from article words
    d = []
    for w in words[:20]:
        if len(d) >= 20:
            break
        d.append(w)
    return d


def run_pipeline(article_text: str) -> dict:
    # Basic fallback behavior: produce a general question and 3 distractors
    article_text = (article_text or '').strip()
    if not article_text:
        return {
            'question': 'No article provided',
            'options': ['A', 'B', 'C', 'D'],
            'correct_index': 0,
            'hints': ['', '', ''],
            'explanation': ''
        }

    # Try to load a saved sample from data/raw/test.csv if exists (for richer demo)
    sample = None
    p = Path('data/raw/test.csv')
    if p.exists():
        try:
            import csv
            rows = list(csv.DictReader(p.open('r', encoding='utf-8')))
            if rows:
                sample = random.choice(rows)
        except Exception:
            sample = None

    if sample:
        q = sample.get('question') or 'What is asked in the passage?'
        opts = [sample.get('A',''), sample.get('B',''), sample.get('C',''), sample.get('D','')]
        # pick correct from sample answer letter
        ans_letter = sample.get('answer','A').strip().upper() if sample.get('answer') else 'A'
        mapping = {'A':0,'B':1,'C':2,'D':3}
        correct_idx = mapping.get(ans_letter, 0)
        hints = [
            'Read the passage introduction for a broad context.',
            'Look at the middle paragraph where the topic is discussed.',
            'The sentence that starts with the phrase "In summary" contains the key fact.'
        ]
        return {
            'question': q,
            'options': opts,
            'correct_index': correct_idx,
            'hints': hints,
            'explanation': 'This explanation is a placeholder generated by the UI stub.'
        }

    # Fallback synthesized options
    question = 'What is the main idea of the passage?'
    cands = _simple_candidates(article_text)
    opts = []
    for i in range(3):
        if i < len(cands):
            opts.append('About ' + cands[i])
        else:
            opts.append(f'Option {i+1}')
    # insert a plausible correct answer
    correct = 'The passage main idea'
    options = [correct] + opts
    random.shuffle(options)
    correct_index = options.index(correct)
    hints = [
        'Hint 1: Consider the general topic.',
        'Hint 2: Look at the second paragraph.',
        'Hint 3: The author states the main point explicitly near the end.'
    ]
    return {
        'question': question,
        'options': options,
        'correct_index': correct_index,
        'hints': hints,
        'explanation': 'Placeholder explanation — replace with Model A output for real runs.'
    }
